[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.production"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables for the Rails app
# Postgres and Redis must be created manually via Railway dashboard
[[deploy.environmentVariables]]
name = "RAILS_ENV"
value = "production"

[[deploy.environmentVariables]]
name = "RAILS_SERVE_STATIC_FILES" 
value = "true"

[[deploy.environmentVariables]]
name = "RAILS_LOG_TO_STDOUT"
value = "true"

[[deploy.environmentVariables]]
name = "WEB_CONCURRENCY"
value = "2"

[[deploy.environmentVariables]]
name = "RAILS_MAX_THREADS"
value = "5"

# Database connection - reference to manually created Postgres service
[[deploy.environmentVariables]]
name = "DATABASE_URL"
value = "${{Postgres.DATABASE_URL}}"

# Redis connection - reference to manually created Redis service  
[[deploy.environmentVariables]]
name = "REDIS_URL"
value = "${{Redis.REDIS_URL}}"

# Rails master key - set this in Railway dashboard as secret
[[deploy.environmentVariables]]
name = "RAILS_MASTER_KEY"
value = "${{RAILS_MASTER_KEY}}"