databases:
  - name: yogomarcas_database
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

services:
  - type: web
    name: yogomarcas_web
    runtime: docker
    repo: https://github.com/Murilo-Araujo/yogomarcas
    dockerfilePath: ./Dockerfile.production
    dockerContext: .
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DEFAULT_HOST_PROTOCOL
        value: https
      - key: MAILGUN_ENABLED
        value: "true"
      - key: RAILS_DB_MIGRATE_ON_STARTUP
        value: "true"
      - key: DATABASE_NAME
        fromDatabase:
          name: yogomarcas_database
          property: database
      - key: DATABASE_HOST
        fromDatabase:
          name: yogomarcas_database
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: yogomarcas_database
          property: port
      - key: DATABASE_USERNAME
        fromDatabase:
          name: yogomarcas_database
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: yogomarcas_database
          property: password